### ISSUE TITLE
Launch BRT Application (BeRTA) with batch/command, setting parameters

### ISSUE THREAD

**Issue by isfmiho** [GrupoDiana/BRTLibrary#1]
I would like to state my wish for launching BeRTA with command line options that can either be entered in a command window or by batch file. puredata provides such options (https://puredata.info/docs/faq/commandline).

My greatest wish: I think it makes most sense to define the sound interface while launching, either by name or by index (compare to "-audioaddoutdev" or "-audiooutdev" in pd).

Maybe there are other options that make sense setting during loading the application, eg. not loading default HRTF/sound file, or even defining your own default files,.... that feature could be extended.

**Comment by dgonzalezt** [comment]
Since version 2.0.0 it is possible to load a settings.json file from the command line. It is only necessary to launch the executable and as a parameter put the path to the file. For example, in Windows, these two options load one of the example files distributed with the application: 
- BeRTA.exe resources/SettingFiles/settings_Basic.json 
or
- BeRTA.exe G:\BeRTA\bin\data\resources\SettingFilesresources/SettingFiles/settings_Basic.json

In the future, on Windows, we would like for example to be able to drag a .json file onto the BeRTA icon and it would load.
